pipeline:
  identifier: Build_digte_whatsapp_1692283710975
  name: Build digte-whatsapp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1692283683298
        repoName: marioeugegomes/digte-whatsapp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: Maven Build
                  spec:
                    shell: Sh
                    command: mvn clear && mvn install
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Maven Package
                  identifier: Maven_Package
                  spec:
                    shell: Sh
                    command: mvn package
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
